---

- hosts: all
  tasks:
  - name: Creates directory and file for logs
    file:
      path: "/home/centos/logs/"
      state: directory
    file:
      path: "/home/centos/logs/log.txt"
      state: touch
    become: yes

  - name: Run the script 1
    script: ./scripts/uptime.sh
    become: yes

  - name: Store file into localhost
    ansible.builtin.fetch:
      src: "/home/centos/logs/log.txt"
      dest: "./logs/"
      flat: yes

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: "/home/centos/logs/log.txt"
      state: absent

  - name: Sending a log
    community.general.mail:
      host: smtp.gmail.com
      port: 587
      username: dizasterwithdezpair
      password: 10.15.Under.Soln
      to: Elizabeth Zaporozhchenko <liza090900@mail.ru>
      subject: Ansible-report
      body: The log is here.
      attach: ./logs/log.txt
    delegate_to: localhost
